### ISSUE TITLE
Request for Pre-trained Model Weights

### ISSUE THREAD

**Issue by fahadshamshad** [CristianoPatricio/concept-based-interpretability-VLM#1]
Hello, thanks for the nice work. Could you kindly provide the pre-trained model weights, or guide me on how I might access them? Thanks.

**Comment by CristianoPatricio** [comment]
Hi @fahadshamshad,

Thank you for your interest in our work.

You can download the model weights from [here](https://ubipt-my.sharepoint.com/:u:/g/personal/cristiano_patricio_ubi_pt/EdHmwc2DKk9DpE3jRQOBA0UBEk2Gy7DuWHJdWVOGuBZ2Rg?e=zj2wac). After download it, you have to unzip the file and copy all `CLIP_XXXXX.pt` files under `CLIP/` folder. Then, create a folder named `output` under the `CLIP/` folder of this repository and paste all the `CLIP_XXXXX.pt` files.

Alternatively, you can obtain these model weights by following the steps described in Section 2 of the [README](https://github.com/CristianoPatricio/concept-based-interpretability-VLM?tab=readme-ov-file#2-training) file.
