### ISSUE TITLE
Problem creating environment from requirements.txt due to unsatisfiable package versions

### ISSUE THREAD

**Issue by sarazatezalo** [CristianoPatricio/concept-based-interpretability-VLM#3]
Hello! I'm trying to set up an environment using the `requirements.txt` provided in this repository, but I'm running into some issues with unsatisfiable package versions. Here’s what I’ve tried and the error I encountered:

Steps to Reproduce:

1. Installed Miniforge3 (Linux-x86_64).
2. Set conda-forge as the main channel.
3. Ran the following command as instructed:
`conda create --name cbi-vlm --file requirements.txt`

**The error that I receive is the following:**
```
Retrieving notices: ...working... done
Channels:

conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:

nothing provides requested zstd ==1.5.2 ha4553b6_0
nothing provides requested zlib ==1.2.13 h5eee18b_0
... (continues with similar errors for all packages)
Could not solve for environment specs
The following packages are incompatible
├─ _libgcc_mutex ==0.1 main is requested and can be installed;
├─ _openmp_mutex ==5.1 1_gnu does not exist (perhaps a typo or a missing channel);
├─ absl-py ==1.3.0 pypi_0 does not exist (perhaps a typo or a missing channel);
├─ aiohttp ==3.8.4 pypi_0 does not exist (perhaps a typo or a missing channel);
├─ aiosignal ==1.3.1 pypi_0 does not exist (perhaps a typo or a missing channel);
├─ albumentations ==1.3.0 pypi_0 does not exist (perhaps a typo or a missing channel);
```

It seems that specific versions requested in requirements.txt are unavailable or not supported on my platform. Is there an alternative way to set up the environment? Or could you provide some guidance on which packages or versions are crucial?

Thank you for your help!

**Comment by CristianoPatricio** [comment]
Hi @sarazatezalo,

Thank you for your interest in our work.
I've tried to create a new conda env with that file and it gives me the same errors, which is strange. Anyway, you can create a conda env with python:

```bash
conda create --name cbi-vlm python=3.10
```

and then install torch:

```bash
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

The only required packages that may be missing are:
- clip
- numpy
- pandas
- scipy
- sklearn

which could be installed manually.

Let me know if this works in the end.

**Comment by sarazatezalo** [comment]
Hi @CristianoPatricio ,

Thanks so much for your help! After installing the libraries you mentioned, the environment is now seemingly working smoothly. I noticed that `tqdm` was also needed but wasn’t listed initially.
Thanks again for the quick response—I appreciate your support!
